package mapreduce

import (
	"encoding/json"
	"hash/fnv"
	"io/ioutil"
	"os"
)

// doMap manages one map task: it reads one of the input files
// (inFile), calls the user-defined map function (mapF) for that file's
// contents, and partitions the output into nReduce intermediate files.
/*doMap管理一个map任务：它读取其中一个输入文件（inFile），
为该文件的内容调用 用户定义的映射函数（mapF），并将输出分区到nReduce中间文件中。*/
func doMap(
	jobName string, // the name of the MapReduce job
	mapTaskNumber int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(file string, contents string) []KeyValue,
) {
	data, err := ioutil.ReadFile(inFile)
	if err != nil {
		debug("read input file err:%v", err)
		return
	}
	kvs := mapF(inFile, string(data))

	reduceFileMap := make(map[int]*os.File)
	for i := 0; i < nReduce; i++ {
		reduceFileName := reduceName(jobName, mapTaskNumber, i)
		reduceFile, err := os.OpenFile(reduceFileName, os.O_CREATE|os.O_RDWR, 0666)
		if err != nil {
			debug("create reduce file err:%v", err)
			return
		}
		defer reduceFile.Close()
		reduceFileMap[i] = reduceFile
	}

	for _, kv := range kvs {
		r := ihash(kv.Key) % nReduce
		enc := json.NewEncoder(reduceFileMap[r])
		enc.Encode(&kv)
	}
	//
	// You will need to write this function.
	//
	// The intermediate output of a map task is stored as multiple
	// files, one per destination reduce task. The file name includes
	// both the map task number and the reduce task number. Use the
	// filename generated by reduceName(jobName, mapTaskNumber, r) as
	// the intermediate file for reduce task r. Call ihash() (see below)
	// on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	// 想出一个如何格式化磁盘上的键/值对的方案可能很棘手，特别是当考虑到键和值都可能包含换行符、引号和您能想到的任何其他字符时。
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	/* 用于将数据序列化到另一端可以正确重构的字节流的一种格式是JSON。
	您不需要使用JSON，但由于减少任务*的输出必须*是JSON，
	在这里熟悉它可能是有用的。您可以使用下面的注释代码将数据结构作为JSON字符串写入文件。
	对应的解码函数可以在common_reduce.go中找到。
	*/
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//

}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
